[VisualTesting] Fix max length of dump name, add possible to create dump subfolders
aquality-automation/aquality-selenium-core-dotnet pull request #96
Opened 2022-01-14 15:11 UTC by MikhailKalyn

Create from https://github.com/aquality-automation/aquality-selenium-core-dotnet/pull/95
Fix conversations

2022-01-14 16:19 UTC, mialeska requested changes

2022-01-17 13:08 UTC, MikhailKalyn commented on Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/DumpManager.cs
> +            var imageFiles = directory.GetFiles($"*.{ImageExtension.ToString().ToLower()}");
There are actually no differences between the JPG and JPEG formats. The only difference is the number of characters used.
System.Drawing.Imaging.ImageFormat class doesn't contain ImageFormat member for Jpg, only Jpeg

same issue for .tif and .tiff formats

if we use the "save" method, then the dump will not contain different formats, only .jpeg
and if the dump is changed manually from the outside, then, in my opinion, this shouldn't affect the work of the framework and method 'compare'
it is the responsibility of the person preparing the dump manually

2022-01-17 16:47 UTC, MikhailKalyn commented on Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/ImageExtensions.cs
> +        public static ImageFormat ConvertImageFormat(string format)
fix

2022-01-17 16:47 UTC, MikhailKalyn commented on Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Visualization/FormDumpTests.cs
> +        public void Should_BePossibleTo_SaveFormDump_WithInvalidExtension(string imageExtension)
fixed

2022-01-17 16:47 UTC, MikhailKalyn commented on Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Visualization/FormDumpTests.cs
> +            Assert.AreEqual(0, pathToDump.Exists? pathToDump.GetFiles().Length : 0, "Dump directory should not contain any files before saving");
fixed

2022-01-18 14:20 UTC, mialeska commented on Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/DumpManager.cs
> +            var imageFiles = directory.GetFiles($"*.{ImageExtension.ToString().ToLower()}");
It's all about consistancy. If I have ".jpg" extension in settings.json, I expect that files with this extension could be used for comparison. If I tell to save in ".jpg" extension but framework saves in ".jpeg" anyways, it looks like a bug for me. ".jpg" extension is used way more often than ".jpeg" in the real world

2022-01-18 15:21 UTC, MikhailKalyn commented on Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/DumpManager.cs
> +            var imageFiles = directory.GetFiles($"*.{ImageExtension.ToString().ToLower()}");
fixed

2022-01-18 15:24 UTC, mialeska commented on Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/ImageFormat.cs
> +        public static ImageFormat Convert(string format)
looks like "Parse"

2022-01-19 08:35 UTC, MikhailKalyn commented on Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/DumpManager.cs
> +            var imageFiles = directory.GetFiles($"*.{ImageExtension.ToString().ToLower()}");
fixed

2022-01-19 08:35 UTC, MikhailKalyn commented on Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/ImageFormat.cs
> +        public static ImageFormat Convert(string format)
fixed

2022-01-19 08:35 UTC, MikhailKalyn commented on Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/ImageFormat.cs
> +using DrawingImageFormat = System.Drawing.Imaging.ImageFormat;
fixed

2022-01-19 09:02 UTC, mialeska approved these changes

2022-01-19 10:36 UTC, merged